import type { Metadata } from 'next'
import { ReactNode } from 'react'
import localFont from 'next/font/local'
import './globals.css'
import MainProvider from '@/app/MainProvider'
import NavBar from '@/app/NavBar'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Issue Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainProvider>
         {children}
          {/*<ThemePanel />*/}
        </MainProvider>
      </body>
    </html>
  )
}
